# Numpy Assignment

In [1]:
# Load libraries
import pandas as pd
import numpy as np

## Q1. Write a function so that the output of a column matrix are powers of the input vector

In [2]:
# numpy.vander function (Generate a Vandermonde matrix)
#Alexandre-Theophile Vandermonde

In [3]:
# Lets define a array
x = np.array([1,2,3,4])
np.vander(x,N=4,increasing=False)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [4]:
x = np.array([1,2,3,4])
N=3
np.vander(x,N,increasing=True)

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  4, 16]])

In [5]:
# Program to generate the same output
x = np.array([3,4,5])
N = len(x)
np.column_stack([x**(N-1-i) for i in range(N)])

array([[ 9,  3,  1],
       [16,  4,  1],
       [25,  5,  1]])

In [6]:
x = np.array([10,20,30,40,50,60,70,80,90,100])     #input array
k = 4  # window

In [7]:
for i in np.arange(len(x)-k+1):
    moving = i+k
    x_move=x[i:i+k]
    print(np.mean(x_move))

25.0
35.0
45.0
55.0
65.0
75.0
85.0


# Q2 Write a function to find moving average in an array over a window:
    Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [8]:
# Given array
x = np.array([3,5,7,2,8,10,11,65,72,81,99,100,150])
window = 3

In [9]:
# To find moving average:
for i in np.arange(len(x)-window+1):
    x_move = x[i:i+window]
    print('moving average of index ['+ str(i)+','+str(i+window)+ ']'+':' +str(np.mean(x_move)))

moving average of index [0,3]:5.0
moving average of index [1,4]:4.666666666666667
moving average of index [2,5]:5.666666666666667
moving average of index [3,6]:6.666666666666667
moving average of index [4,7]:9.666666666666666
moving average of index [5,8]:28.666666666666668
moving average of index [6,9]:49.333333333333336
moving average of index [7,10]:72.66666666666667
moving average of index [8,11]:84.0
moving average of index [9,12]:93.33333333333333
moving average of index [10,13]:116.33333333333333
